### PR TITLE
Fix vault couldn't get a value

### PR DESCRIPTION
**Pull request by mopemope**
I was checking the vault backend and couldn't get the value, so I fixed it.

### CODE REVIEW

**Comment by axiomista** [comment]
We would love to see this get merged if possible, as it fixes an issue that prevents one of our projects from adopting confita fully for our config management. 
CC: @asdine @danieljheetch

**Comment by asdine** [comment]
cc @skateinmars ?

**Comment by philippgille** [comment]
Hi @mopemope !

I added some changes to your branch, basically separating the KV secrets engine v1 vs v2 handling to make sure v1 handling doesn't break, and added tests for the v2 handling: https://github.com/heetch/confita/pull/86

Would that work for you?
Happy about feedback from you @axiomista as well!

**Comment by skateinmars** [comment]
To add to @philippgille's comment:

First, apologies for the extra late reply.
We only use environment variables internally, so this library can be considered mostly deprecated.
It also suffers some design issues, for instance the inclusion of every dependency needed for all the supported backends.

In any case, thanks a lot for the initial submission and for the attention!

**Comment by axiomista** [comment]
> Happy about feedback from you @axiomista as well!

Thank you for your additional work here, @philippgille! Nice to be protected from regression by tests. ^-^ We can use #86 as-is; my teammate @ckawasaki-isp left a 👍🏽 on that one. 

Thanks also for letting us know that you're not using confita internally anymore, @skateinmars. It is still serving our config-gathering purposes, so I expect we'll have it in our projects for a while yet, but good to know. You've been really helpful.

**Comment by philippgille** [comment]
Fixed in #86

**Pull request closed without merging**
