### PR TITLE
struct backend

### PR DESCRIPTION
**Pull request by aecepoglu**
this is my attempt at a fix for issue #24 

The work isn't finished yet (except for int, string and bool types) but I wanted to open the PR earlier to get some feedback on whether there is a quicker way of doing this, as I feel like I'm doing a lot of manual work.

### CODE REVIEW

**Comment by rydrman** [comment]
Perhaps you could simply marshal the struct to JSON and then use the JSON decoder to pull the data back out when requested. Not really the most efficient method but the complex ruleset of turning go data structures into config-like data is tried and true in the `engcoding/json` package.

**Comment by aecepoglu** [comment]
it would make things significantly easier though: I'll do it like you suggested.

Is it OK for confita backends to depend on each other? Because I'll  be utilizing the JSON backend to do this

**Comment by asdine** [comment]
@aecepoglu What kind of use cases do you see using this backend?
If i wanted dynamic data from an arbitrary source i'd rather use a `map[string]interface{}` i guess.
I'm afraid having loading from any struct would bring too much magic

**Comment by aecepoglu** [comment]
@asdine this is a fix for https://github.com/heetch/confita/issues/24, a 3 month old issue

**Comment by YassineE** [comment]
This issue was created a long time ago and I don't remember why i have created it (tbh i forgot to delete it). I'll do it now. But we really appreciate the time you took to contribute to our project. 
Feel free to pick another issue and submit a PR.

**Pull request closed without merging**
